// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpUsBFiHrbifbmLPFLPo7jnNPkWjm4Qxg',
    appId: '1:108570294986:web:2309102483bf89b8845233',
    messagingSenderId: '108570294986',
    projectId: 'le-messie',
    authDomain: 'le-messie.firebaseapp.com',
    storageBucket: 'le-messie.firebasestorage.app',
    measurementId: 'G-G9QT0NZDZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvgXQHXNELUUFsUFj9Ocs8JBsnPse389U',
    appId: '1:108570294986:android:844ab6027559c072845233',
    messagingSenderId: '108570294986',
    projectId: 'le-messie',
    storageBucket: 'le-messie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYZuqhovXF0nu2-quqZcmAp7o6jSc4Ok',
    appId: '1:108570294986:ios:98758b538b66dd46845233',
    messagingSenderId: '108570294986',
    projectId: 'le-messie',
    storageBucket: 'le-messie.firebasestorage.app',
    iosBundleId: 'com.lili.bebe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTYZuqhovXF0nu2-quqZcmAp7o6jSc4Ok',
    appId: '1:108570294986:ios:98758b538b66dd46845233',
    messagingSenderId: '108570294986',
    projectId: 'le-messie',
    storageBucket: 'le-messie.firebasestorage.app',
    iosBundleId: 'com.lili.bebe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpUsBFiHrbifbmLPFLPo7jnNPkWjm4Qxg',
    appId: '1:108570294986:web:4a9db7d40138a6a7845233',
    messagingSenderId: '108570294986',
    projectId: 'le-messie',
    authDomain: 'le-messie.firebaseapp.com',
    storageBucket: 'le-messie.firebasestorage.app',
    measurementId: 'G-P3QDJMPLJK',
  );
}
