// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5JxcwmFbbg4SHWp4jfAgMhVuG2B-Q7As',
    appId: '1:366889753325:web:00875818cd50fa76208ae4',
    messagingSenderId: '366889753325',
    projectId: 'light-64a3a',
    authDomain: 'light-64a3a.firebaseapp.com',
    storageBucket: 'light-64a3a.firebasestorage.app',
    measurementId: 'G-VWM206L78E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgd-zxp4qUoAkLok8Pnw2tyd1bexE_4lo',
    appId: '1:366889753325:android:67810149be9f0f2a208ae4',
    messagingSenderId: '366889753325',
    projectId: 'light-64a3a',
    storageBucket: 'light-64a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4sxi3OY5jX8fzv1fLvahkuMAWt4gHOZc',
    appId: '1:366889753325:ios:fd36f6a8d7ac005a208ae4',
    messagingSenderId: '366889753325',
    projectId: 'light-64a3a',
    storageBucket: 'light-64a3a.firebasestorage.app',
    iosBundleId: 'com.lili.lightapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4sxi3OY5jX8fzv1fLvahkuMAWt4gHOZc',
    appId: '1:366889753325:ios:fd36f6a8d7ac005a208ae4',
    messagingSenderId: '366889753325',
    projectId: 'light-64a3a',
    storageBucket: 'light-64a3a.firebasestorage.app',
    iosBundleId: 'com.lili.lightapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5JxcwmFbbg4SHWp4jfAgMhVuG2B-Q7As',
    appId: '1:366889753325:web:85dc6d13b03c27de208ae4',
    messagingSenderId: '366889753325',
    projectId: 'light-64a3a',
    authDomain: 'light-64a3a.firebaseapp.com',
    storageBucket: 'light-64a3a.firebasestorage.app',
    measurementId: 'G-THFPR5VKE5',
  );

}